### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by madsbredholt** [sematext/logagent-js#206]
2020-03-02T11:05:13.016Z v3.0.21 pid[6] Container 4c41c2667758bd56da960ff10957c6c4575e24591f2cb1edcf9b5aafb7215ce6 /tmp-xb-backup setting LOGSENE_ENABLED=true
Please contact support@sematext.com to report the error:
UncaughtException:TypeError: Cannot read property 'slice' of undefined
  TypeError: Cannot read property 'slice' of undefined
    at BufferList.shallowSlice (/usr/local/lib/node_modules/@sematext/logagent/node_modules/bl/bl.js:210:29)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/@sematext/logagent/node_modules/docker-loghose/lib/parser.js:77:37)
    at Array.forEach (<anonymous>)
    at DestroyableTransform.publish (/usr/local/lib/node_modules/@sematext/logagent/node_modules/docker-loghose/lib/parser.js:75:13)
    at DestroyableTransform.parse [as _transform] (/usr/local/lib/node_modules/@sematext/logagent/node_modules/docker-loghose/lib/parser.js:67:10)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/@sematext/logagent/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/@sematext/logagent/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/local/lib/node_modules/@sematext/logagent/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/@sematext/logagent/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/@sematext/logagent/node_modules/readable-stream/lib/_stream_writable.js:334:11)

**Comment by adnanrahic** [comment]
Hey @madsbredholt! Thanks for letting us know about this. I'm debugging this issue right away. Can you let me know how to exactly replicate this bug? What did you do and what is your configuration when this started happening? Thanks! :smile:

**Comment by madsbredholt** [comment]
Hi,

I am not sure how to replicate it.

I have not been able to figure out how to reproduce.

I have attached our docker stack file and logagent config files.

Regards
Mads

________________________________
Fra: Adnan Rahić <notifications@github.com>
Sendt: tirsdag 3. mars 2020 10:49
Til: sematext/logagent-js <logagent-js@noreply.github.com>
Kopi: Mads bredholt <mads.bredholt@staminagroup.no>; Mention <mention@noreply.github.com>
Emne: Re: [sematext/logagent-js] Cannot read property 'slice' of undefined (#206)


Hey @madsbredholt<https://github.com/madsbredholt>! Thanks for letting us know about this. I'm debugging this issue right away. Can you let me know how to exactly replicate this bug? What did you do and what is your configuration when this started happening? Thanks! 😄

**Comment by adnanrahic** [comment]
Okay. I've tested the latest release with Docker Compose and running it with Docker from the command line. I'll take a look at your specific Docker Stack configuration, and get back to you.

**Comment by adnanrahic** [comment]
Hey @madsbredholt. I've tested every single case with your specific configuration and did not manage to reproduce the issue.

However, I did manage to find the reason why your configuration was not shipping parsed files from the host. PR #207 fixes it. I'll let you know once the fix is released.

**Comment by megastef** [comment]
@adnanrahic the original error is probably a problem reading the log data from docker socket. ‘docker-loghose/lib/parser.js:77:37’ - Did it happen while ‘docherd’ service made a restart? Try to restart dockerd to reproduce it.

**Comment by madsbredholt** [comment]
Ok,

Thanks

Regards Mads
________________________________
Fra: Adnan Rahić <notifications@github.com>
Sendt: tirsdag 3. mars 2020 17:47
Til: sematext/logagent-js <logagent-js@noreply.github.com>
Kopi: Mads bredholt <mads.bredholt@staminagroup.no>; Mention <mention@noreply.github.com>
Emne: Re: [sematext/logagent-js] Cannot read property 'slice' of undefined (#206)


Hey @madsbredholt<https://github.com/madsbredholt>. I've tested every single case with your specific configuration and did not manage to reproduce the issue.

However, I did manage to find the reason why your configuration was not shipping parsed files from the host. PR #207<https://github.com/sematext/logagent-js/pull/207> fixes it. I'll let you know once the fix is released.

**Comment by madsbredholt** [comment]
We will try and get back to you.

Regards
Mads

________________________________
Fra: Megastef <notifications@github.com>
Sendt: tirsdag 3. mars 2020 23:22
Til: sematext/logagent-js <logagent-js@noreply.github.com>
Kopi: Mads bredholt <mads.bredholt@staminagroup.no>; Mention <mention@noreply.github.com>
Emne: Re: [sematext/logagent-js] Cannot read property 'slice' of undefined (#206)


@adnanrahic<https://github.com/adnanrahic> the original error is probably a problem reading the log data from docker socket. ‘docker-loghose/lib/parser.js:77:37’ - Did it happen while ‘docherd’ service made a restart? Try to restart dockerd to reproduce it.

**Comment by adnanrahic** [comment]
Sure, I'll wait for that. In the meantime, I've pushed version 3.0.22 that fixes your other issue, mentioned through email. :smile:

**Comment by otisg** [comment]
@madsbredholt can we assume this is no longer an issue for you?

**Comment by madsbredholt** [comment]
We have not had the opportunity to look at it for a while.

We will let you know if it occurs again 🙂

Regards
Mads

________________________________
Fra: Otis Gospodnetić <notifications@github.com>
Sendt: tirsdag 5. mai 2020 22:51
Til: sematext/logagent-js <logagent-js@noreply.github.com>
Kopi: Mads bredholt <mads.bredholt@staminagroup.no>; Mention <mention@noreply.github.com>
Emne: Re: [sematext/logagent-js] Cannot read property 'slice' of undefined (#206)


@madsbredholt<https://github.com/madsbredholt> can we assume this is no longer an issue for you?
