### ISSUE TITLE
logagent failling on using azure eventhub plugin

### ISSUE THREAD

**Issue by Qwin** [sematext/logagent-js#283]
```
Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'fromEnqueuedTime' of undefined
      at InputAzureEventhub.startAsync (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/input/azure-event-hub.js:73:34)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
} reason:  TypeError: Cannot read property 'fromEnqueuedTime' of undefined
    at InputAzureEventhub.startAsync (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/input/azure-event-hub.js:73:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Cannot read property 'fromEnqueuedTime' of undefined
    at InputAzureEventhub.startAsync (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/input/azure-event-hub.js:73:34)
```

Getting the above error when using the azure event hub plugin, I think its related to the eventhub library (node package 5.x) that is used. (wrong version maybe ? or its my node version) 

using Mac and node 14.x. I do want to say that it does work for my co-worker which has a linux box and node 12.x. so there is something fishy going on.  Tried to force downgrade of the library eventhub within the logagent package however that caused other issues.

**Comment by otisg** [comment]
Hm, not sure.  Don't have the bandwidth or ability to look into this.  If you find a solution we'd welcome a PR.

**Comment by Qwin** [comment]
PR #285 fixes this issue.

**Comment by otisg** [comment]
Thanks!
